### PR TITLE
Add new blog post resource: Postmortems.

### PR DESCRIPTION
**Pull request by android10**
Hello @dastergon! As we agreed here: https://github.com/dastergon/postmortem-templates/pull/6

I would love to add a new resource to the list if possible:

- [Learn out of mistakes. Postmortems to the rescue.](https://fernandocejas.com/2020/03/21/learn-out-of-mistakes-postmortems/)

One more time, thank you very much for gathering and collecting such amount of useful resources.

Cheers

### CODE REVIEW

**Comment by dastergon** [comment]
Hey, thanks :) can you move the URL to the bottom of the list?

**Comment by dastergon** [comment]
ping @android10

**Comment by android10** [comment]
@dastergon sorry for the delay. Fixed.

Thanks also for collecting such valuable information and letting me to be part of this. :heart:

**Comment by dastergon** [comment]
Great, thanks :)

**Pull request merged**
