### PR TITLE
Remove more broken links

### PR DESCRIPTION
**Pull request by tuxinaut**
Hi, me again, I checked with [lychee](https://github.com/lycheeverse/lychee) found more broken links, and removed them.

```
❯ ./lychee ~/workspace/awesome-sre/README.md
⚡ http://distributed-systems-observability-ebook.humio.com/ (error sending request for url (http://distributed-systems-observability-ebook.humio.com/): error trying to connect: dns error: failed to lookup address information: Name or service not known)
⚡ http://some.ops4devs.info/ (error sending request for url (http://some.ops4devs.info/): error trying to connect: dns error: failed to lookup address information: Name or service not known)
🚫 https://www.meetup.com/site-reliability/ [404 Not Found]
🚫 https://rackn.com/sre-white-paper/ [404 Not Found]
```

### CODE REVIEW

**Comment by dastergon** [comment]
Thanks a lot @tuxinaut!

**Comment by tuxinaut** [comment]
:point_up: Had the same in mind :smile:

**Comment by dastergon** [comment]
Feel free to send a PR if you have some spare time to do it @tuxinaut :)

**Comment by tuxinaut** [comment]
Already on it :)

**Comment by paulfantom** [comment]
@tuxinaut there is a github action for checking links that prometheus-operator is using. You can take a look at the implementation in https://github.com/prometheus-operator/prometheus-operator/blob/master/.github/workflows/ci.yaml#L24-L33

**Comment by tuxinaut** [comment]
@paulfantom thx for the hint :smile: Already finished it.

https://github.com/tuxinaut/awesome-sre/blob/master/.github/workflows/lychee.yml

**Pull request merged**
