### PR TITLE
Add Lychee Link Checker

### PR DESCRIPTION
**Pull request by tuxinaut**
This Pull Request is going to implement the [Lychee Broken Link Checker](https://github.com/marketplace/actions/lychee-broken-link-checker) action

The action is configured to run on each push and scheduled every seven days.

It will check all links in the README.md and automatically creates issues when it finds broken links.

Please feel free to make any changes to the PR so that it fits your needs.

### CODE REVIEW

**Comment by dastergon** [comment]
Thanks a lot for your contribution @tuxinaut :)

**Comment by dastergon** [comment]
@tuxinaut it looks like the Action is failing, can you take a look and send a follow-up PR with the update?

**Comment by tuxinaut** [comment]
:sob: I will try to have a look at it today.

**Comment by tuxinaut** [comment]
@dastergon this should hopefully fix the issues  #102

**Pull request merged**
