### PR TITLE
Removing dead link for "The Remediation Ballet"

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @dastergon 

just removing a dead link for "The Remediation Ballet".

Cheers!

### CODE REVIEW

**Comment by dastergon** [comment]
Hi @spekulatius, 

I found a copy here: https://digital-forensics.sans.org/summit-archives/file/summit-archive-1492182549.pdf

Feel free to update the hyperlink instead.

**Comment by spekulatius** [comment]
Hey @dastergon 

awesome find. I looked only www and didn't find anything. I've updated the link :+1: 

Cheers,
Peter

**Comment by dastergon** [comment]
Thanks! Is it possible to squeeze the commits into one?

**Comment by spekulatius** [comment]
Done @dastergon

**Comment by dastergon** [comment]
Thanks a lot @spekulatius! 👍

**Comment by spekulatius** [comment]
No worries, happy to help out @dastergon

**Pull request merged**
